with open(r'D:\the-exile-king\review_art_ollama.py', 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Remove stray lines 867-921 (the prompts sitting in the middle of main())
clean_lines = lines[:866] + lines[921:]

new_prompts = [
    '    "jonathan_commander": "ONE PERSON ONLY, solo portrait, waist-up, Jonathan son of Saul, bronze age Levantine prince and warrior, dark hair, handsome features, rich blue-purple cloak over linen tunic, leather vest, composite bow in hand, quiver on back, bronze short sword at hip, noble brave expression, standing confidently, Mediterranean complexion, hand-painted historical illustration, watercolor and ink on aged parchment, board game card art, centered composition, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "philistine_lord_commander": "ONE PERSON ONLY, solo portrait, waist-up, Philistine lord, bronze age Levantine city-state ruler, dark hair, rich embroidered tunic, bronze scale armor, purple cloak, bronze sword, authoritative expression, standing with regal bearing, Mediterranean complexion, hand-painted historical illustration, watercolor and ink on aged parchment, board game card art, centered composition, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "shield_bearer_david": "ONE PERSON ONLY, solo portrait, waist-up, David\'s shield bearer, bronze age Levantine heavy infantry, dark hair, linen tunic with leather armor, brown cloak, large round hide shield with bronze rim, bronze short sword, protective stance, determined expression, Mediterranean complexion, hand-painted historical illustration, watercolor and ink on aged parchment, board game card art, centered composition, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "shield_bearer_jonathan": "ONE PERSON ONLY, solo portrait, waist-up, Jonathan\'s shield bearer, bronze age Levantine warrior, dark hair, white linen tunic with dark border, leather vest, brown cloak, large round hide shield held high, bronze sword at hip, protective stance, determined expression, Mediterranean complexion, hand-painted historical illustration, watercolor and ink on aged parchment, board game card art, centered composition, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "shield_bearer_achish": "ONE PERSON ONLY, solo portrait, waist-up, Philistine shield bearer, bronze age Levantine heavy infantryman, dark hair, linen tunic with bronze scale armor, brown cloak, large rectangular hide shield with bronze rim, long spear, bronze helmet, imposing defensive stance, Mediterranean complexion, hand-painted historical illustration, watercolor and ink on aged parchment, board game card art, centered composition, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "shield_bearer_ekron": "ONE PERSON ONLY, solo portrait, waist-up, Ekron shield bearer, bronze age Levantine heavy infantryman, dark hair, linen tunic with leather shoulder armor, brown cloak, round hide shield held high, bronze short sword, disciplined defensive stance, Mediterranean complexion, hand-painted historical illustration, watercolor and ink on aged parchment, board game card art, centered composition, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "giant_achish": "ONE PERSON ONLY, solo portrait, waist-up, Philistine giant warrior from Gath, bronze age Levantine giant, enormous build, dark hair and beard, worn leather tunic, bronze scales on shoulders, small shield, massive bronze-tipped spear, fierce expression, towering menacing figure, Mediterranean complexion, hand-painted historical illustration, watercolor and ink on aged parchment, board game card art, centered composition, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "swordsman_jonathan": "ONE PERSON ONLY, solo portrait, waist-up, Jonathan\'s swordsman guard, bronze age Levantine elite infantry, dark hair, white linen tunic with leather vest, brown cloak, bronze short sword raised, small hide shield, disciplined attack stance, Mediterranean complexion, hand-painted historical illustration, watercolor and ink on aged parchment, board game card art, centered composition, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "swordsman_achish": "ONE PERSON ONLY, solo portrait, waist-up, Philistine swordsman of Gath, bronze age Levantine infantry, dark hair, linen tunic with leather vest, brown wool cloak, bronze short sword with leaf-shaped blade in hand, small round hide shield on arm, leather wrapped grip, alert expression, standing ready, Mediterranean complexion, hand-painted historical illustration, watercolor and ink on aged parchment, board game card art, centered composition, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "swordsman_ekron": "ONE PERSON ONLY, solo portrait, waist-up, Ekron swordsman, bronze age Levantine infantry, dark hair, linen tunic with leather shoulder piece, brown cloak tied at neck, bronze short sword in hand, small hide shield on arm, determined expression, standing on coastal ground, Mediterranean complexion, hand-painted historical illustration, watercolor and ink on aged parchment, board game card art, centered composition, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "spearman_jonathan": "ONE PERSON ONLY, solo portrait, waist-up, Jonathan\'s spearman guard, bronze age Levantine elite infantry, dark hair, white linen tunic with leather shoulder guards, brown cloak wrapped, long wooden spear with bronze tip held upright, small hide shield at side, knife at waist, alert disciplined expression, Mediterranean complexion, hand-painted historical illustration, watercolor and ink on aged parchment, board game card art, centered composition, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "spearman_achish": "ONE PERSON ONLY, solo portrait, waist-up, Philistine spearman of Gath, bronze age Levantine warrior, dark hair, linen tunic with leather shoulder piece, brown cloak tied at neck, long wooden spear with bronze tip held in both hands, small hide shield slung across back, knife at waist, sandals, focused expression, standing on rocky ground, Mediterranean complexion, hand-painted historical illustration, watercolor and ink on aged parchment, board game card art, centered composition, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "spearman_ekron": "ONE PERSON ONLY, solo portrait, waist-up, Ekron spearman, bronze age Levantine warrior, dark hair, linen tunic with leather armor, brown cloak, long wooden spear with bronze tip held taut, small hide shield, steady formation stance, Mediterranean complexion, hand-painted historical illustration, watercolor and ink on aged parchment, board game card art, centered composition, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "slinger_ekron": "ONE PERSON ONLY, solo portrait, waist-up, Ekron slinger, bronze age Levantine skirmisher, dark hair, simple linen tunic with leather vest, worn brown cloak, leather sling in hand with pouch of stones at hip, pouch of smooth stones at waist, small knife, alert predatory expression, standing on coastal sand, Mediterranean complexion, hand-painted historical illustration, watercolor and ink on aged parchment, board game card art, centered composition, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "archer_jonathan": "ONE PERSON ONLY, solo portrait, waist-up, Jonathan\'s archer, bronze age Levantine archer, dark hair, simple linen tunic with leather vest, brown cloak, short composite bow drawn with arrow nocked, quiver of arrows slung across back, knife at waist, sandals, drawing bow with focused precision, Mediterranean complexion, hand-painted historical illustration, watercolor and ink on aged parchment, board game card art, centered composition, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "archer_achish": "ONE PERSON ONLY, solo portrait, waist-up, Philistine archer of Ekron, bronze age Levantine archer, dark hair, linen tunic with leather vest, short composite bow in hand with arrow nocked, quiver on back, knife at waist, focused expression, standing ready, Mediterranean complexion, hand-painted historical illustration, watercolor and ink on aged parchment, board game card art, centered composition, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "chariot_ekron": "ONE PERSON ONLY, solo portrait, waist-up, Ekron charioteer, bronze age Levantine warrior, dark hair, linen tunic with leather armor, brown cloak flowing, standing beside bronze-rimmed chariot, spear in hand, weathered determined expression, Mediterranean complexion, hand-painted historical illustration, watercolor and ink on aged parchment, board game card art, centered composition, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "card_front_david": "hand-painted royal portrait of David the future king of Israel, young bronze age Levantine commander, dark curly hair and trimmed beard, simple linen tunic with leather chest piece, brown wool cloak pinned at shoulder with bronze brooch, bronze short sword at hip, leather sling tucked in belt, shepherd\'s staff in hand, determined watchful expression, standing on rocky Judean hillside under overcast sky, aged parchment background, ink outlines with muted watercolor wash, board game card art, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "card_front_jonathan": "hand-painted noble portrait of Jonathan son of Saul, bronze age Levantine prince and warrior, dark hair, handsome features, rich blue-purple cloak over linen tunic, leather vest, composite bow in hand, quiver on back, bronze short sword at hip, noble brave expression, standing confidently, aged parchment background, ink outlines with muted watercolor wash, board game card art, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "card_front_achish": "hand-painted regal portrait of Achish lord of Gath, bronze age Levantine Philistine ruler, dark hair, rich purple cloak over linen tunic, bronze chest plate, bronze sword at hip, stern unreadable expression, seated authority on folding stool, flanked by spearmen, warm lamplight, aged parchment background, ink outlines with muted watercolor wash, board game card art, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "card_front_philistine_lord": "hand-painted regal portrait of the Philistine lord of Ekron, bronze age Levantine ruler, dark hair, embroidered tunic, bronze scale armor, purple cloak, bronze sword, authoritative expression, standing with regal bearing, Mediterranean complexion, aged parchment background, ink outlines with muted watercolor wash, board game card art, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "swordsmen-advance": "scene in illuminated manuscript style, bronze age Levantine Israelite swordsmen advancing in formation, bronze short swords raised, hide shields overlapping, dust at their heels, linen tunics and leather vests, determined expressions, aged parchment background, ink outlines with muted watercolor wash in ochre and faded crimson, hand-painted historical illustration, board game card art, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "swordsmen-formation": "scene in illuminated manuscript style, bronze age Levantine Israelite swordsmen in shield wall formation, shields locked, spears resting on shoulders, grim defensive stance, linen tunics, leather vests, aged parchment background, ink outlines with muted watercolor wash in umber and faded crimson, hand-painted historical illustration, board game card art, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "spear-wall": "scene in illuminated manuscript style, bronze age Levantine Israelite spearmen in tight formation, long wooden spears with bronze tips angled outward, shields locked, braced defensive stance, linen tunics, leather armor, grim expressions, aged parchment background, ink outlines with muted watercolor wash in umber and faded crimson, hand-painted historical illustration, board game card art, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "spearman-formation": "scene in illuminated manuscript style, bronze age Levantine Israelite spearmen advancing in lockstep, spears angled forward, shields overlapping, discipline and order, linen tunics, brown cloaks, leather armor, aged parchment background, ink outlines with muted watercolor wash in ochre and umber, hand-painted historical illustration, board game card art, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "spearman-screen": "scene in illuminated manuscript style, bronze age Levantine spearmen holding ground, shields forward, spears thrusting, protecting allies behind them, linen tunics, leather vests, determined expressions, aged parchment background, ink outlines with muted watercolor wash in umber and faded gold, hand-painted historical illustration, board game card art, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "circle-and-strike": "scene in illuminated manuscript style, bronze age Levantine Israelite slingers in mobile skirmish formation, leather slings raised, stones in pouches, light armor, crouched mobile stances, alert expressions, aged parchment background, ink outlines with muted watercolor wash in ochre and umber, hand-painted historical illustration, board game card art, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "stone-volley": "scene in illuminated manuscript style, bronze age Levantine Israelite slingers releasing a volley of stones, leather slings snapping forward, projectiles arcing through air, concentrated fire on one target, linen tunics, leather vests, focused expressions, aged parchment background, ink outlines with muted watercolor wash in ochre and umber, hand-painted historical illustration, board game card art, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "archer-volley": "scene in illuminated manuscript style, bronze age Levantine Israelite archers on ridge aiming forward, composite bows drawn, arrows ready to loose, linen tunics, leather arm bracers, quivers on backs, aged parchment background, ink outlines with muted watercolor wash in ochre and faded ochre, hand-painted historical illustration, board game card art, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "archer-formation": "scene in illuminated manuscript style, bronze age Levantine Israelite archers in disciplined formation, bows lowered watching, ready for overwatch, linen tunics, leather vests, alert expressions, aged parchment background, ink outlines with muted watercolor wash in ochre and faded gold, hand-painted historical illustration, board game card art, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "scout-recon": "scene in illuminated manuscript style, bronze age Levantine Israelite scouts moving swiftly through rocky terrain, light clothing, scanning horizon, short spears and slings, alert watchful expressions, aged parchment background, ink outlines with muted watercolor wash in ochre and faded ochre, hand-painted historical illustration, board game card art, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "scout-formation": "scene in illuminated manuscript style, bronze age Levantine Israelite scouts hidden in rocky ambush, covered by cloaks and scrub, one scout peering over rock with hand raised signal to hold, linen tunics, worn cloaks, alert expressions, aged parchment background, ink outlines with muted watercolor wash in umber and ochre, hand-painted historical illustration, board game card art, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "guard-formation": "scene in illuminated manuscript style, Jonathan\'s loyal guards in shield wall formation, spears locked, shields overlapping, disciplined elite infantry, white linen tunics with dark borders, leather vests, brown cloaks, grim expressions, aged parchment background, ink outlines with muted watercolor wash in umber and faded indigo, hand-painted historical illustration, board game card art, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "jonathans-mark": "scene in illuminated manuscript style, Jonathan\'s elite archer taking careful aim at a distant target, composite bow drawn, one eye closed in concentration, arrow aligned, linen tunic, leather bracers, brown cloak, focused precise expression, aged parchment background, ink outlines with muted watercolor wash in ochre and faded gold, hand-painted historical illustration, board game card art, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "perfect-shot": "scene in illuminated manuscript style, Jonathan\'s elite archer standing perfectly still drawing bow to full draw, arrow nocked, target visible in distance, linen tunic, leather vest, brown cloak, focused expression, aged parchment background, ink outlines with muted watercolor wash in ochre and amber, hand-painted historical illustration, board game card art, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "giants-might": "scene in illuminated manuscript style, Philistine giant warrior crushing enemy shield with massive spear, enormous build, worn leather tunic, bronze scales on shoulders, small shield, massive bronze-tipped spear, fierce expression, towering menacing figure, aged parchment background, ink outlines with muted watercolor wash in umber and faded crimson, hand-painted historical illustration, board game card art, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "unstoppable": "scene in illuminated manuscript style, Philistine giant warrior crushing through enemy line, massive spear raised, enemy scattering before him, enormous build, simple tunic, bronze shoulder scales, fierce expression, aged parchment background, ink outlines with muted watercolor wash in umber and faded crimson, hand-painted historical illustration, board game card art, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "berserker-rage": "scene in illuminated manuscript style, wounded Philistine giant warrior going berserk, massive spear swinging, armor dented, furious expression, enemies recoiling, enormous build, worn tunic, bloodied but fighting harder, aged parchment background, ink outlines with muted watercolor wash in umber and faded crimson, hand-painted historical illustration, board game card art, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "ekron-archer-command": "scene in illuminated manuscript style, Ekron archers firing coordinated volley, composite bows drawn, arrows loosing in unison, linen tunics, leather vests, quivers on backs, focused concerted expressions, aged parchment background, ink outlines with muted watercolor wash in ochre and faded ochre, hand-painted historical illustration, board game card art, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "ekron-archer-formation-1": "scene in illuminated manuscript style, Ekron archers opening volley before advance, bows drawn, arrows flying ahead of marching infantry, linen tunics, leather bracers, quivers on backs, aged parchment background, ink outlines with muted watercolor wash in ochre and umber, hand-painted historical illustration, board game card art, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "ekron-archer-formation-2": "scene in illuminated manuscript style, Ekron archers targeting same enemy position with combined fire, multiple arrows arcing toward one tile, focused concerted bombardment, linen tunics, leather vests, quivers, aged parchment background, ink outlines with muted watercolor wash in ochre and faded crimson, hand-painted historical illustration, board game card art, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "chariot-charge": "scene in illuminated manuscript style, Ekron chariot smashing through enemy line, bronze-rimmed wheels, horse or runners straining, spear lowered for impact, linen tunic, leather armor, brown cloak flowing, determined expression, aged parchment background, ink outlines with muted watercolor wash in ochre and faded crimson, hand-painted historical illustration, board game card art, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "chariot-formation-1": "scene in illuminated manuscript style, Ekron chariot breaking through enemy shield wall, bronze-rimmed wheels, spear thrusting forward, pushing enemies aside, linen tunic, leather armor, brown cloak, aggressive expression, aged parchment background, ink outlines with muted watercolor wash in umber and ochre, hand-painted historical illustration, board game card art, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "chariot-formation-2": "scene in illuminated manuscript style, Ekron charioteer riding past after striking, wheels spinning, cloak billowing, weapon still raised, linen tunic, leather armor, brown cloak, hit-and-run tactic, aged parchment background, ink outlines with muted watercolor wash in ochre and faded gold, hand-painted historical illustration, board game card art, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "shield-wall": "scene in illuminated manuscript style, shield bearers locking shields, large round hide shields overlapping, bronze rims, protective formation, steadfast unyielding expression, linen tunics, leather armor, brown cloaks, aged parchment background, ink outlines with muted watercolor wash in umber and ochre, hand-painted historical illustration, board game card art, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "phalanx-advance": "scene in illuminated manuscript style, shield bearer and allies advancing carefully, shield held high, moving as one solid wall, linen tunics, leather armor, brown cloaks, determined expressions, aged parchment background, ink outlines with muted watercolor wash in umber and faded indigo, hand-painted historical illustration, board game card art, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "card_back": "blank aged parchment card back, rectangular, ornate decorative ink border in dark brown, corner ornaments, medieval manuscript border style, no text, hand-painted board game card texture, aged warm parchment, family friendly, NOT medieval, NOT fantasy, NOT European",\n',
    '    "sword-sheath": "bronze age leather sword sheath, worn brown leather, bronze tip protector, isolated, hand-painted illustration, watercolor, transparent background, NOT medieval, NOT fantasy, NOT European",\n',
    '    "quiver": "bronze age leather quiver with arrows, worn leather, fletched arrows, isolated, hand-painted illustration, watercolor, transparent background, NOT medieval, NOT fantasy, NOT European",\n',
    '    "bronze-helm": "bronze age simple bronze helmet, rounded cap with nose guard, isolated, hand-painted illustration, watercolor, transparent background, NOT medieval, NOT fantasy, NOT European",\n',
    '    "bronze-greaves": "bronze age bronze shin guards, simple pair, aged patina, isolated, hand-painted illustration, watercolor, transparent background, NOT medieval, NOT fantasy, NOT European",\n',
    '    "leather-belt": "bronze age simple leather belt, worn brown leather, bronze buckle, isolated, hand-painted illustration, watercolor, transparent background, NOT medieval, NOT fantasy, NOT European",\n',
    '    "commander-aura-marker": "soft glowing circle on ground, commander presence area, warm golden light, board game UI element, transparent background, hand-painted illustration, NOT medieval, NOT fantasy, NOT European",\n',
    '    "activation-token": "small wooden token shape, aged warm parchment color, dark ink border outline, flat board game token, game UI element, isolated on transparent background, family friendly",\n',
    '    "lost-pile-marker": "small marker disk, aged parchment with dark X mark, board game token style, game UI element, isolated on transparent background, family friendly",\n',
    '    "setup-sheet": "game setup reference sheet, aged parchment background, dark ink text boxes, checkmark list style, board game reference card, hand-painted texture, no background",\n',
]

# Insert into EXPECTED_PROMPTS before line 282 (which is the last prompt entry)
# Line 283 (index 282) is the closing }
insert_idx = 282
final_lines = clean_lines[:insert_idx] + new_prompts + clean_lines[insert_idx:]

with open(r'D:\the-exile-king\review_art_ollama.py', 'w', encoding='utf-8') as f:
    f.writelines(final_lines)

print('Fixed.')
